#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr  1 12:38:52 2020

@author: daniela
"""

# Imprime en ese caso "Es palindroma"
s='anas'

palabra = str(input('ingrese alguna palabra: '))
if str(palabra) == str(palabra)[::-1] :
    print('es palíndromo')
else:
    print('no es palíndromo')